### ISSUE TITLE
group filter does not work ?

### ISSUE THREAD

**Issue by mohicanb** [wordpress-connector-for-mobilizon/connector-mobilizon#12]
Hello and thank you for your module.
We have a Mobilizon group here : https://mobilizon.fr/@liberons_nos_ordis
And a Wordpress web site (v 5.9.3) where, after installing your extension with URL setting = https://mobilizon.fr
we have inputed this code `[connector-mobilizon-events-list events-count=3 group-name="liberons_nos_ordis"]`
in a post but it shows nothing.
same code in a widget where it displays : "The events could not be loaded!" (see at the bottom of this page : https://liberonsnosordis.org/ )
It works with no group-name but then shows all events on the server with is not what we want.

**Comment by dwaxweiler** [comment]
Hello @mohicanb,
Thanks for your report! Your shortcode looks correct. I could reproduce this issue, and released version 0.9.1 with a fix. Let me know whether it works for you after updating.
Kind regards,
Daniel

**Comment by mohicanb** [comment]
Hello, strangely now the widget works, but not the inclusion [in the post](https://liberonsnosordis.org/prochaine-intervention/).

**Comment by dwaxweiler** [comment]
@mohicanb, try to delete and recreate the shortcode you have.

**Comment by mohicanb** [comment]
I works, thank you (there was a html format tag inside the source code)
