### ISSUE TITLE
Add event picture

### ISSUE THREAD

**Issue by dwaxweiler** [wordpress-connector-for-mobilizon/connector-mobilizon#4]
A user has requested via e-mail that they would be happy to optionally display the events' picture in a widget or a shortcut.

**Comment by kamazeuci** [comment]
I think this is a must... AFAIK mobilizon-connector only displays events info in the form of text. The ideal would be to get events images, that would be beautiful.
thanks.

**Comment by dwaxweiler** [comment]
I have been working on this recently and got stuck with the caching. I was not able to cache the pictures as base64-encoded string in the database; Maybe, I went over a limit. I need to think of another solution.

**Comment by dwaxweiler** [comment]
This feature will land with the next release.
